### ISSUE TITLE
Toggle Filters for Audit Search Row

### ISSUE THREAD

**Issue by fernandez7108** [anteneh72/UltimoTLS#19]
Not properly sorting the rows by the columns selected

**Comment by fernandez7108** [comment]
Fix filters had to be updated:
timestamp to timestamp.$date
interface to interface1

**Comment by fernandez7108** [comment]
timestamp.$date is giving an error and no longer working properly

Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 0-10 ['timestamp] in expression ['timestamp].
http://errors.angularjs.org/1.3.0/$parse/lexerr?p0=Unterminated%20quote&p1=s%200-10%20%5B'timestamp%5D&p2='timestamp
    at REGEX_STRING_REGEXP (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:80:12)
    at Lexer.throwError (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:11601:11)
    at Lexer.readString (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:11743:10)
    at Lexer.lex (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:11527:14)
    at Parser.parse (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:11773:30)
    at $parse (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:12411:39)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1676:17
    at Array.forEach (native)
    at ngEventHandler (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1671:20)
    at invokeLinkFn (http://localhost:8383/UltimoTLS/lib/js/angular/angular.js:8111:9) <a href="" ng-click="reverse = !reverse; predicate='timestamp.$date'">
